---
title: "Hunt Strategy"
author: "Brett Stacy"
date: "19 June 2019"
output: pdf_document
---

```{r, echo=F}
library(casal)
library(earthfish)
```



## Tasks for Paul

### 
Try my TOA_bug_5.R and figure out why my assessment year implementation isn't working. Tag recaptures not showing up in outputlog.


### 
By the end of the week, please run your model with flounder life history parameters. Or perhaps updated TOP LHPs. Either way, run a scenario you know worked for your TOP migration paper but with different LHPs and plot the SSB for OM and AM. 



### 
Run TOA_bug_1.R for one iteration (don't run plot chunk at end). OK to change file path.

look at the warnings at the end. Does the one about NAs mean anything to you?



### 
the thing with tag age frequency overlaping catch not matching up.



### 
Can you go through the settings related to biomass like para\$ass\$estim_initialization.B0 to see if they are reasonable for my lower value of recruitment (and subsequent biomass).
  
  
  
### 
Can you go though my match function and see if there is anything missing?


### 
Only when I manually calculate SSB for the OM does it line up with the SSB from CASAL. Why would this be the case for TOA and not for TOP?



